/***************************************************************/
/*                                                             */
/* Copyright (C) Sidney 2024-2026. All rights reserved.        */
/* Written by Sidney.                                          */
/* Distributed under terms of the GNU General Public License.  */
/*                                                             */
/***************************************************************/
/*
 * Nordzy icon theme runtime (ring 0).
 * Decodes the packed PNG subset (nordzy_icons.h, generated by
 * tools/pack_icons.py) through the kernel libpng/zlib pair and draws
 * icons with alpha blending. Decoded sprites are cached forever — the
 * whole theme subset is ~50 KB compressed / a few hundred KB RGBA.
 */

#include "nordzy_icons.h"
#include <png.h>
#include <setjmp.h>
#include <stdint.h>
#include <string.h>
#include "kernel/mem/kheap.h"
#include "drivers/video/gfx.h"

/* ── decoded-sprite cache ──────────────────────────────────── */
typedef struct {
    char       name[48];
    int        w, h;
    uint32_t*  px;      /* (a<<24)|(r<<16)|(g<<8)|b */
} nz_sprite_t;

static nz_sprite_t cache[64];
static int         cache_n = 0;

/* ── libpng glue ───────────────────────────────────────────── */
typedef struct { const unsigned char* d; uint32_t len, pos; } nz_src_t;

static void nz_read_fn(png_structp png, png_bytep buf, png_size_t n) {
    nz_src_t* s = (nz_src_t*)png_get_io_ptr(png);
    if (s->pos + n > s->len) n = s->len - s->pos;
    memcpy(buf, s->d + s->pos, n);
    s->pos += (uint32_t)n;
}

static void* nz_malloc_fn(png_structp png, png_alloc_size_t sz) {
    (void)png;
    return kmalloc((size_t)(sz ? sz : 1));
}
static void nz_free_fn(png_structp png, void* p) {
    (void)png;
    if (p) kfree(p);
}

static int nz_decode(const unsigned char* d, uint32_t len,
                     int* ow, int* oh, uint32_t** opx) {
    if (len < 8 || png_sig_cmp(d, 0, 8)) return 0;

    png_structp png = png_create_read_struct_2(PNG_LIBPNG_VER_STRING,
                        0, 0, 0, 0, nz_malloc_fn, nz_free_fn);
    if (!png) return 0;
    png_infop info = png_create_info_struct(png);
    if (!info || setjmp(png_jmpbuf(png))) {
        png_destroy_read_struct(&png, info ? &info : 0, 0);
        return 0;
    }

    nz_src_t src; src.d = d; src.len = len; src.pos = 0;
    png_set_read_fn(png, &src, nz_read_fn);
    png_read_info(png, info);

    png_byte ctype = png_get_color_type(png, info);
    png_byte depth = png_get_bit_depth(png, info);
    if (ctype == PNG_COLOR_TYPE_PALETTE)            png_set_expand(png);
    if (ctype == PNG_COLOR_TYPE_GRAY && depth < 8)  png_set_expand(png);
    if (png_get_valid(png, info, PNG_INFO_tRNS))    png_set_expand(png);
    if (depth == 16)                                png_set_strip_16(png);
    if (ctype == PNG_COLOR_TYPE_GRAY ||
        ctype == PNG_COLOR_TYPE_GRAY_ALPHA)         png_set_gray_to_rgb(png);

    int passes = png_set_interlace_handling(png);
    png_read_update_info(png, info);

    int w = (int)png_get_image_width(png, info);
    int h = (int)png_get_image_height(png, info);
    int ch   = (int)png_get_channels(png, info);
    size_t rb = (size_t)png_get_rowbytes(png, info);
    if (w <= 0 || h <= 0 || w > 512 || h > 512 || (ch != 3 && ch != 4)) {
        png_destroy_read_struct(&png, &info, 0);
        return 0;
    }

    uint32_t* px = (uint32_t*)kmalloc((size_t)w * h * 4);
    uint8_t*  row = (uint8_t*)kmalloc(rb);
    if (!px || !row) {
        if (px) kfree(px);
        if (row) kfree(row);
        png_destroy_read_struct(&png, &info, 0);
        return 0;
    }

    for (int p = 0; p < passes; p++) {
        for (int y = 0; y < h; y++) {
            png_read_row(png, (png_bytep)row, 0);
            if (p != passes - 1) continue;
            uint32_t* dst = px + (size_t)y * w;
            for (int x = 0; x < w; x++) {
                const uint8_t* s8 = row + (size_t)x * ch;
                uint32_t a = (ch == 4) ? s8[3] : 255;
                dst[x] = ((uint32_t)a << 24)
                       | ((uint32_t)s8[0] << 16)
                       | ((uint32_t)s8[1] << 8)
                       |  (uint32_t)s8[2];
            }
        }
    }

    kfree(row);
    png_destroy_read_struct(&png, &info, 0);
    *ow = w; *oh = h; *opx = px;
    return 1;
}

/* find or decode the sprite for an EigenOS app name */
static nz_sprite_t* nz_lookup(const char* app) {
    for (int i = 0; i < cache_n; i++)
        if (strcmp(cache[i].name, app) == 0) return &cache[i];

    for (unsigned e = 0; e < sizeof(nz_icons) / sizeof(nz_icons[0]); e++) {
        if (strcmp(nz_icons[e].name, app) != 0) continue;
        if (cache_n >= (int)(sizeof(cache) / sizeof(cache[0]))) return 0;
        nz_sprite_t* sp = &cache[cache_n];
        strncpy(sp->name, app, sizeof(sp->name) - 1);
        sp->name[sizeof(sp->name) - 1] = 0;
        sp->px = 0;
        if (!nz_decode(nz_blob + nz_icons[e].off, nz_icons[e].len,
                       &sp->w, &sp->h, &sp->px))
            return 0;   /* decode failed: don't cache, procedural fallback */
        cache_n++;
        return sp;
    }
    return 0;           /* not themed: procedural fallback */
}

/* Draw the themed icon at (x,y) scaled to `size`. Returns 0 when the app
 * has no themed icon so callers can fall back to the procedural glyphs. */
int icon_theme_draw(const char* app, int x, int y, int size) {
    if (!app || !app[0] || size <= 0) return 0;
    nz_sprite_t* sp = nz_lookup(app);
    if (!sp || !sp->px) return 0;

    for (int dy = 0; dy < size; dy++) {
        int sy = dy * sp->h / size;
        const uint32_t* row = sp->px + (size_t)sy * sp->w;
        for (int dx = 0; dx < size; dx++) {
            int sx = dx * sp->w / size;
            uint32_t c = row[sx];
            uint32_t a = c >> 24;
            if (a == 0) continue;
            gfx_blend_pixel(x + dx, y + dy, c & 0xFFFFFF, (uint8_t)a);
        }
    }
    return 1;
}
